version: '3'

volumes:
  mongo_data:
    driver: local

networks:
  system_traefik:
    external: true
  kzk-connect:
    external: true

services:
  mongodb:
    image: mongo:4.2.8
    volumes:
      - mongo_data:/data/db
    networks:
      - default
    hostname: mongodb.dev.test
    ports:
      - 27017:27017

  simva-api:
    build: ./
    command: [ "npm", "run", "dev" ]
    stdin_open: true
    tty: true
    environment:
      #DEBUG
      DEBUG: false
      #NODE
      NODE_ENV: development
      NODE_EXTRA_CA_CERTS: /app/DemoCA.crt
      #EXTERNAL URL
      EXTERNAL_URL: https://simva.dev.test
      #SIMVA API (SELF)
      SIMVA_API_HOST: simva-api.dev.test
      SIMVA_API_PORT: 443
      SIMVA_API_PROTOCOL: https
      ADMIN_USERNAME: admin
      ADMIN_EMAIL: admin@dev.test
      ADMIN_PASSWORD: password
      #MONGO DB
      MONGO_HOST: mongodb.dev.test
      MONGO_DB: /simva
      LTI_MONGO_DB: /lti_simva
      #KAFKA
      KAFKA_HOST: kafka1.dev.test
      KAFKA_PORT: 9092
      #MINIO
      MINIO_URL: https://minio.dev.test/
      MINIO_API_URL: minio-api.dev.test
      MINIO_SSL: true
      MINIO_PORT: 443
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: secret
      MINIO_BUCKET: traces
      MINIO_TOPICS_DIR: kafka-topics
      MINIO_TRACES_TOPIC: traces
      MINIO_OUTPUTS_DIR: outputs
      MINIO_TRACES_FILE: traces.json
      MINIO_PRESIGNED_URL_FILE_EXPIRATION_TIME : 1h 
      #LIMESURVEY
      LIMESURVEY_HOST: limesurvey.external.test
      LIMESURVEY_PROTOCOL: https
      LIMESURVEY_PORT: 443
      LIMESURVEY_EXTERNAL: https://limesurvey.dev.test/
      LIMESURVEY_ADMIN_USER: admin
      LIMESURVEY_ADMIN_PASSWORD: secret
      #SSO KEYCLOAK
      SSO_ENABLED: true
      SSO_REALM: simva
      SSO_CLIENT_ID: simva
      SSO_CLIENT_SECRET: secret
      SSO_STUDENT_ALLOWED_ROLE: true
      SSO_TEACHING_ASSISTANT_ALLOWED_ROLE: true
      SSO_TEACHER_ALLOWED_ROLE: true
      SSO_RESEARCHER_ALLOWED_ROLE: true
      SSO_SSL_REQUIRED: external
      SSO_PUBLIC_CLIENT: false
      SSO_HOST: sso.dev.test
      SSO_PROTOCOL: https
      SSO_PORT: 443
      SSO_ADMIN_USER: administrator
      SSO_ADMIN_PASSWORD: administrator
      #A2
      A2_HOST: a2
      A2_PROTOCOL: http
      A2_PORT: 3000
      A2_ADMIN_USER: root
      A2_ADMIN_PASSWORD: password
      A2_EXTERNAL: https://analytics.dev.test
      #ANALYTICS BACKEND
      ANALYTICSBACKEND_API: /api/proxy/gleaner
      #LTI
      LTI_PLATFORM_CLIENT_ID: lti_platform
      LTI_PLATFORM_SIGNING_KEY: secret
      LTI_PLATFORM_DB_NAME: /lti_simva
      LTI_PLATFORM_DB_USER:  root
      LTI_PLATFORM_DB_PASSWORD: password
      #STORAGE
      SIMVA_STORAGE_PATH: /storage/
      #SHLINK
      SHLINK_SERVER_HOST: shlink.dev.test
      SHLINK_PORT: 443
      SHLINK_PROTOCOL: https
      SHLINK_SERVER_API_KEY: password
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules #exclude node_modules 
    depends_on:
      - mongodb
    hostname: simva-api.dev.test
    networks:
      - default
      - system_traefik
      - kzk-connect
    labels:
      traefik.enable: true
      traefik.port: 3000
      traefik.frontend.rule: Host:simva-api.dev.test
