version: '3'

volumes:
  mongo_data:
    driver: local

networks:
  system_traefik:
    external: true
  kzk-connect:
    external: true

services:
  mongodb:
    image: mongo:4.0
    volumes:
      - mongo_data:/data/db
    networks:
      - default
    hostname: mongodb
    ports:
      - 27017:27017

  simva-api:
    image: node:8
    command: bash -c "cd /app && chmod +x docker-startup.sh && ./docker-startup.sh"
    stdin_open: true
    tty: true
    environment:
      EXTERNAL_URL: https://simva.e-ucm.es/
      MONGO_HOST: mongodb
      MONGO_DB: /simva
      KAFKA_HOST: kafka1
      KAFKA_PORT: 9092
      KAFKA_TOPIC: traces
      MINIO_URL: https://minio.simva.e-ucm.es/
      LIMESURVEY_PROTOCOL: http
      LIMESURVEY_HOST: limesurvey-dev
      LIMESURVEY_PORT: 80
      LIMESURVEY_EXTERNAL: https://limesurvey.simva.e-ucm.es/
      LIMESURVEY_ADMIN_USER: admin
      LIMESURVEY_ADMIN_PASSWORD: password
      A2_HOST: analytics.e-ucm.es
      A2_ADMIN_USER: root
      A2_ADMIN_PASSWORD: EiK4iSWyFqzHjG42Dn8ifVDSGd83PRIe
      NODE_EXTRA_CA_CERTS: /app/DemoCA.crt
    volumes:
      - ./:/app
    depends_on:
      - mongodb
    hostname: simva-api.dev.test
    networks:
      - default
      - system_traefik
      - kzk-connect
    labels:
      traefik.enable: true
      traefik.port: 3000
      traefik.frontend.rule: "Host:api.simva.e-ucm.es"
