/**
 * @fileoverview Service for admin xAPI/LRS operations.
 * Handles the retrieval of xAPI statements from the whole Learning Record Store
 * without any activity or session scoping.
 *
 * This service allows administrators to query the statements generated by the
 * frontend interactions (games, surveys, trackers) across all the studies.
 *
 * @module services/admin/adminLRS
 * @requires @/lib/errors/appErrors
 * @requires @/lib/utils/LRSclient
 */

import { NotImplementedError } from "@/lib/errors/appErrors";
import { lrsclient } from "@/lib/utils/LRSclient";

/**
 * Retrieves xAPI statements from the whole LRS using the given query.
 *
 * @async
 * @function getStatements
 * @param {any} query - LRS query parameters for filtering the statements
 * @returns {Promise<Object>} The raw LRS response with the statements and the more URL
 * @throws {NotImplementedError} If the LRS integration is not configured
 *
 * @example
 * const statements = await getStatements({ verb: 'https://...', since: '2024-01-01...' });
 */
export async function getStatements(query: any): Promise<Object> {
	if(!lrsclient.isEnabled()) {
		throw new NotImplementedError("LRS integration is not configured");
	}
	lrsclient.normalizeStatementsQuery(query);
	const client = await lrsclient.getLRSClient();
	if(query.more) {
		return await client.getMoreStatements(query.more);
	}
	return await client.getStatementByQuery(query);
}

/**
 * Retrieves additional xAPI statements from the whole LRS using a continuation token.
 *
 * @async
 * @function getMoreStatements
 * @param {string} more - The more URL returned in the previous statements response
 * @returns {Promise<Object>} The raw LRS response with the next batch of statements
 * @throws {NotImplementedError} If the LRS integration is not configured
 *
 * @example
 * const statements = await getMoreStatements('https://lrs.example/xapi/statements/more/abc');
 */
export async function getMoreStatements(more: string): Promise<Object> {
	if(!lrsclient.isEnabled()) {
		throw new NotImplementedError("LRS integration is not configured");
	}
	const client = await lrsclient.getLRSClient();
	return await client.getMoreStatements(more);
}

/**
 * Sends xAPI statements to the whole LRS without activity scoping.
 *
 * The statements are forwarded as-is, generating an identifier for those
 * that do not provide one. Unlike the activity-scoped path, no simlet/session
 * context is injected and the statements are not sent to the Kafka traces topic.
 *
 * @async
 * @function sendStatements
 * @param {any} body - A single xAPI statement or an array of xAPI statements
 * @returns {Promise<number[]>} The ids of the statements sent to the LRS
 * @throws {NotImplementedError} If the LRS integration is not configured
 *
 * @example
 * const ids = await sendStatements([{ id: '...', actor: {}, verb: {}, object: {} }]);
 */
export async function sendStatements(body: any): Promise<number[]> {
	if(!lrsclient.isEnabled()) {
		throw new NotImplementedError("LRS integration is not configured");
	}
	return await lrsclient.sendStatements(body);
}